name: campnn
channels:
  - defaults
  - conda-forge
  - pytorch
  - pip
dependencies:
  - python=3.10.0
  - pandas
  - numpy
  - tqdm
  - tensorflow
  - tensorflow-probability
  - pytorch
  - torchvision 
  - torchaudio 
  - jupyterlab
  - yfinance
  - matplotlib
  - openpyxl
  - ipywidgets
  - cvxopt
  - pmdarima
  - networkx
  - seaborn
  - scipy